////////////////////////////////////////////////////////////////////////////////
// NOTE : Generated by slothjson. It is NOT supposed to modify this file.
////////////////////////////////////////////////////////////////////////////////
#ifndef __config_20190711175239_h__
#define __config_20190711175239_h__

#include "slothjson.h"

namespace slothjson {

struct tcp_config_t
{
    bool no_delay;
    bool keep_alive;

    void skip_no_delay() { __skip_no_delay = true; }
    void skip_keep_alive() { __skip_keep_alive = true; }

    bool json_has_no_delay() const { return __json_has_no_delay; }
    bool json_has_keep_alive() const { return __json_has_keep_alive; }

    tcp_config_t();
    tcp_config_t& operator=(const tcp_config_t& obj_val);
    bool operator==(const tcp_config_t& obj_val) const;
    bool encode(allocator_t& alloc, rapidjson::Value& json_val) const;
    bool decode(const rapidjson::Value& json_val);

private:
    bool __skip_no_delay;
    bool __skip_keep_alive;

    bool __json_has_no_delay;
    bool __json_has_keep_alive;
};

bool encode(const tcp_config_t& obj_val, allocator_t& alloc, rapidjson::Value& json_val);
bool decode(const rapidjson::Value& json_val, tcp_config_t& obj_val);

struct ssl_config_t
{
    bool verify;
    bool verify_hostname;
    std::string cert;
    std::string key;
    std::string key_password;
    std::string cipher;
    bool prefer_server_cipher;
    std::string sni;
    std::vector<std::string > alpn;
    std::string alpn_str;
    bool reuse_session;
    int session_timeout;

    void skip_verify() { __skip_verify = true; }
    void skip_verify_hostname() { __skip_verify_hostname = true; }
    void skip_cert() { __skip_cert = true; }
    void skip_key() { __skip_key = true; }
    void skip_key_password() { __skip_key_password = true; }
    void skip_cipher() { __skip_cipher = true; }
    void skip_prefer_server_cipher() { __skip_prefer_server_cipher = true; }
    void skip_sni() { __skip_sni = true; }
    void skip_alpn() { __skip_alpn = true; }
    void skip_alpn_str() { __skip_alpn_str = true; }
    void skip_reuse_session() { __skip_reuse_session = true; }
    void skip_session_timeout() { __skip_session_timeout = true; }

    bool json_has_verify() const { return __json_has_verify; }
    bool json_has_verify_hostname() const { return __json_has_verify_hostname; }
    bool json_has_cert() const { return __json_has_cert; }
    bool json_has_key() const { return __json_has_key; }
    bool json_has_key_password() const { return __json_has_key_password; }
    bool json_has_cipher() const { return __json_has_cipher; }
    bool json_has_prefer_server_cipher() const { return __json_has_prefer_server_cipher; }
    bool json_has_sni() const { return __json_has_sni; }
    bool json_has_alpn() const { return __json_has_alpn; }
    bool json_has_alpn_str() const { return __json_has_alpn_str; }
    bool json_has_reuse_session() const { return __json_has_reuse_session; }
    bool json_has_session_timeout() const { return __json_has_session_timeout; }

    ssl_config_t();
    ssl_config_t& operator=(const ssl_config_t& obj_val);
    bool operator==(const ssl_config_t& obj_val) const;
    bool encode(allocator_t& alloc, rapidjson::Value& json_val) const;
    bool decode(const rapidjson::Value& json_val);

private:
    bool __skip_verify;
    bool __skip_verify_hostname;
    bool __skip_cert;
    bool __skip_key;
    bool __skip_key_password;
    bool __skip_cipher;
    bool __skip_prefer_server_cipher;
    bool __skip_sni;
    bool __skip_alpn;
    bool __skip_alpn_str;
    bool __skip_reuse_session;
    bool __skip_session_timeout;

    bool __json_has_verify;
    bool __json_has_verify_hostname;
    bool __json_has_cert;
    bool __json_has_key;
    bool __json_has_key_password;
    bool __json_has_cipher;
    bool __json_has_prefer_server_cipher;
    bool __json_has_sni;
    bool __json_has_alpn;
    bool __json_has_alpn_str;
    bool __json_has_reuse_session;
    bool __json_has_session_timeout;
};

bool encode(const ssl_config_t& obj_val, allocator_t& alloc, rapidjson::Value& json_val);
bool decode(const rapidjson::Value& json_val, ssl_config_t& obj_val);

struct zlog_t
{
    std::string conf;
    std::string default_category;

    void skip_conf() { __skip_conf = true; }
    void skip_default_category() { __skip_default_category = true; }

    bool json_has_conf() const { return __json_has_conf; }
    bool json_has_default_category() const { return __json_has_default_category; }

    zlog_t();
    zlog_t& operator=(const zlog_t& obj_val);
    bool operator==(const zlog_t& obj_val) const;
    bool encode(allocator_t& alloc, rapidjson::Value& json_val) const;
    bool decode(const rapidjson::Value& json_val);

private:
    bool __skip_conf;
    bool __skip_default_category;

    bool __json_has_conf;
    bool __json_has_default_category;
};

bool encode(const zlog_t& obj_val, allocator_t& alloc, rapidjson::Value& json_val);
bool decode(const rapidjson::Value& json_val, zlog_t& obj_val);

struct config_t
{
    zlog_t logger;
    std::string local_addr;
    uint16_t local_port;
    std::string remote_addr;
    uint16_t remote_port;
    std::vector<std::string > password;
    std::map<std::string, std::string > pwd;
    std::string run_type;
    int rt;
    ssl_config_t ssl;
    tcp_config_t tcp;

    void skip_logger() { __skip_logger = true; }
    void skip_local_addr() { __skip_local_addr = true; }
    void skip_local_port() { __skip_local_port = true; }
    void skip_remote_addr() { __skip_remote_addr = true; }
    void skip_remote_port() { __skip_remote_port = true; }
    void skip_password() { __skip_password = true; }
    void skip_pwd() { __skip_pwd = true; }
    void skip_run_type() { __skip_run_type = true; }
    void skip_rt() { __skip_rt = true; }
    void skip_ssl() { __skip_ssl = true; }
    void skip_tcp() { __skip_tcp = true; }

    bool json_has_logger() const { return __json_has_logger; }
    bool json_has_local_addr() const { return __json_has_local_addr; }
    bool json_has_local_port() const { return __json_has_local_port; }
    bool json_has_remote_addr() const { return __json_has_remote_addr; }
    bool json_has_remote_port() const { return __json_has_remote_port; }
    bool json_has_password() const { return __json_has_password; }
    bool json_has_pwd() const { return __json_has_pwd; }
    bool json_has_run_type() const { return __json_has_run_type; }
    bool json_has_rt() const { return __json_has_rt; }
    bool json_has_ssl() const { return __json_has_ssl; }
    bool json_has_tcp() const { return __json_has_tcp; }

    config_t();
    config_t& operator=(const config_t& obj_val);
    bool operator==(const config_t& obj_val) const;
    bool encode(allocator_t& alloc, rapidjson::Value& json_val) const;
    bool decode(const rapidjson::Value& json_val);

private:
    bool __skip_logger;
    bool __skip_local_addr;
    bool __skip_local_port;
    bool __skip_remote_addr;
    bool __skip_remote_port;
    bool __skip_password;
    bool __skip_pwd;
    bool __skip_run_type;
    bool __skip_rt;
    bool __skip_ssl;
    bool __skip_tcp;

    bool __json_has_logger;
    bool __json_has_local_addr;
    bool __json_has_local_port;
    bool __json_has_remote_addr;
    bool __json_has_remote_port;
    bool __json_has_password;
    bool __json_has_pwd;
    bool __json_has_run_type;
    bool __json_has_rt;
    bool __json_has_ssl;
    bool __json_has_tcp;
};

bool encode(const config_t& obj_val, allocator_t& alloc, rapidjson::Value& json_val);
bool decode(const rapidjson::Value& json_val, config_t& obj_val);

} // namespace slothjson

#endif // __config_20190711175239_h__